<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TheLongDarkPath>S:/Steam/steamapps/common/TheLongDark</TheLongDarkPath>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <DebugType>none</DebugType>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <MelonLoaderPath>$(TheLongDarkPath)/MelonLoader/net6</MelonLoaderPath>
        <ManagedPath>$(TheLongDarkPath)/MelonLoader/Managed</ManagedPath>
        <Il2CppPath>$(TheLongDarkPath)/MelonLoader/Il2CppAssemblies</Il2CppPath>
        <AssemblySearchPaths>$(AssemblySearchPaths);$(MelonLoaderPath);$(ManagedPath);$(Il2CppPath);</AssemblySearchPaths>
        <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <Reference>
            <Private>False</Private>
        </Reference>
    </ItemDefinitionGroup>

    <ItemGroup>
        <Reference Include="MelonLoader" />
        <Reference Include="0Harmony" />
        <Reference Include="Assembly-CSharp" />
        <Reference Include="UnityEngine" />
        <Reference Include="UnityEngine.CoreModule" />
        <Reference Include="UnityEngine.UI" />
        <Reference Include="Il2Cppmscorlib" />
        <Reference Include="Il2CppInterop.Runtime" />
    </ItemGroup>

</Project>
